### ISSUE TITLE
Sensor won't connect to medusa

### ISSUE THREAD

**Issue by Desaydrone** [IDmedia/hass-medusa#4]
Hi, i try to use your interessing integration, but without success.

here the error in the HA log : 

```log
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 725, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/medusa/sensor.py", line 83, in update
    tv_shows = self.get_infos(self.protocol, self.host, self.port, self.token, self.web_root, 'future')
  File "/config/custom_components/medusa/sensor.py", line 132, in get_infos
    ifs_movies = requests.get(url).json()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 917, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: [Errno Expecting value] 
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="robots" content="noindex, nofollow">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="theme-color" content="#333333">
    <title>Medusa</title>
    <base href="http://localhost:1881/">
    
        <link rel="shortcut icon" href="images/ico/favicon.ico?v=2">
        <link rel="icon" sizes="16x16 32x32 64x64" href="images/ico/favicon.ico">
        <link rel="icon" type="image/png" sizes="196x196" href="images/ico/favicon-196.png">
        <link rel="icon" type="image/png" sizes="160x160" href="images/ico/favicon-160.png">
        <link rel="icon" type="image/png" sizes="96x96" href="images/ico/favicon-96.png">
        <link rel="icon" type="image/png" sizes="64x64" href="images/ico/favicon-64.png">
        <link rel="icon" type="image/png" sizes="32x32" href="images/ico/favicon-32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="images/ico/favicon-16.png">
        <link rel="apple-touch-icon" sizes="152x152" href="images/ico/favicon-152.png">
        <link rel="apple-touch-icon" sizes="144x144" href="images/ico/favicon-144.png">
        <link rel="apple-touch-icon" sizes="120x120" href="images/ico/favicon-120.png">
        <link rel="apple-touch-icon" sizes="114x114" href="images/ico/favicon-114.png">
        <link rel="apple-touch-icon" sizes="76x76" href="images/ico/favicon-76.png">
        <link rel="apple-touch-icon" sizes="72x72" href="images/ico/favicon-72.png">
        <link rel="apple-touch-icon" href="images/ico/favicon-57.png">
        <style>
        [v-cloak] {
            display: none !important;

}
        </style>

        <link rel="stylesheet" type="text/css" href="css/vendors.css?18512"/>

        <link rel="stylesheet" type="text/css" href="css/vender.min.css?18512"/>
        <link rel="stylesheet" type="text/css" href="css/bootstrap-formhelpers.min.css?18512"/>
        <link rel="stylesheet" type="text/css" href="css/browser.css?18512" />
        <link rel="stylesheet" type="text/css" href="css/lib/jquery-ui-1.10.4.custom.min.css?18512" />
        <link rel="stylesheet" type="text/css" href="css/lib/jquery.qtip-2.2.1.min.css?18512"/>
        <link rel="stylesheet" type="text/css" href="css/style.css?18512"/>
        <link rel="stylesheet" type="text/css" href="css/themed.css?18512" />
        <link rel="stylesheet" type="text/css" href="css/themed.css?18512" />
        <link rel="stylesheet" type="text/css" href="css/print.css?18512" />
        <link rel="stylesheet" type="text/css" href="css/country-flags.css?18512"/>
        
    </head>
    

<body data-controller="FixME" data-action="FixME" api-key="dcef1ac002f180cabb1dc350018a07b3" web-root="">
    <div id="vue-wrap" class="container-fluid">
        <load-progress-bar v-if="showsLoading" v-bind="{display: showsLoading.display, current: showsLoading.current, total: showsLoading.total}"></load-progress-bar>

        <div v-if="globalLoading" class="text-center">
            <h3>Loading&hellip;</h3>
            If this is taking too long,<br>
            <i style="cursor: pointer;" @click="globalLoading = false;">click here</i> to show the page.
        </div>

        <div v-cloak :style="globalLoading ? { opacity: '0 !important' } : undefined">
            <app-header></app-header>
            <sub-menu></sub-menu>
          
<!-- BEGIN ALERTS -->
<!-- END ALERTS -->


            <div id="content-row" class="row">
                <component :is="pageComponent || 'div'" id="content-col" class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    
<h1 class="header">{{header}}</h1>
<div class="align-center">
You have reached this page by accident, please check the url.
</div>

                </component>
            </div><!-- /content -->

            <app-footer v-if="$store.state.auth.isAuthenticated"></app-footer>
            <scroll-buttons></scroll-buttons>

          </div><!-- /globalLoading wrapper -->

        </div>
        

        <script type="text/javascript" src="js/vendors.js?18512"></script>
        <script type="text/javascript" src="js/vendors~date-fns.js?18512"></script>
        <script type="text/javascript" src="js/medusa-runtime.js?18512"></script>

        <script type="text/javascript" src="js/index.js?18512"></script>

        <script type="text/javascript" src="js/vender.min.js?18512"></script>
        <script type="text/javascript" src="js/lib/bootstrap-formhelpers.min.js?18512"></script>
        <script type="text/javascript" src="js/lib/formwizard.js?18512"></script>
        <script type="text/javascript" src="js/lib/lazyload.js?18512"></script>

        <script type="text/javascript" src="js/parsers.js?18512"></script>

        <script type="text/javascript" src="js/config/init.js?18512"></script>

        <script type="text/javascript" src="js/common/init.js?18512"></script>

        <script type="text/javascript" src="js/browser.js?18512"></script>

        <script type="text/javascript" src="js/notifications.js?18512"></script>

        <!-- Moved to main, as I can't add it to display-show.vue, because vue templates don't allow script tags. -->
        <!-- <script type="text/javascript" src="js/ajax-episode-search.js?18512"></script> -->
        <!-- <script type="text/javascript" src="js/ajax-episode-subtitles.js?18512"></script> -->
        <script>
            // Used to get username to the app.js and header
            window.username = '';

            // [Temporary] Used by the QualityChooser component on some pages

            if ('False' === 'True') {
                Vue.config.devtools = true;
                Vue.config.performance = true;
            }
        </script>
        <script>
            // @TODO: Remove this before v1.0.0
            if (!window.loadMainApp && window.globalVueShim) {
                window.globalVueShim();
            }
        </script>
        
<script>
window.app = {};
window.app = new Vue({
    store,
    router,
    el: '#vue-wrap',
    metaInfo: {
        title: '404'
    },
    data() {
        return {
            header: 'Oops'
        };
    }
});
>

    </body>
</html>
: 1
```

My sensor

```yaml
  - platform: medusa
    name: medusa
    host: !secret medusa_host
    token: !secret medusa_token
    port: !secret medusa_port
    sort: date
```

For what i can see, the api seems not be use, i try in command line the api responding

**Comment by IDmedia** [comment]
Please update to the latest version and let me know if the issue persists. If installed through HACS hit the "update information" button and you should be prompted to update.

If that doesn't work try to visit the API directly to see if it's working:
`http://192.168.1.60:8081/api/v1/YOUR_TOKEN?cmd=future&type=today|soon`

**Comment by Desaydrone** [comment]
... i think i got a problem, api V1 doesn't work, i use V2 for test and it work... don't find yet why v1 not responding

```shell
curl --include \                                                                                                                            ✔ 
     --header "Content-Type: application/json" \
     --header "Accept: application/json; charset=UTF-8" \
  'http://localhost:8081/api/v2/series?api_key=MY_API_KEY'
```

This working for the v2, need to find v1 :p

**Comment by Desaydrone** [comment]
OK now V1 api works
