### ISSUE TITLE
Some error with date

### ISSUE THREAD

**Issue by Desaydrone** [IDmedia/hass-medusa#6]
Hello, it's me again,

Now that api v1 seems work for me i got another error, i'm in 24h day and not 12h

```log
022-03-26 12:46:45 ERROR (MainThread) [homeassistant.helpers.entity] Update for sensor.medusa fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 535, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 744, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/medusa/sensor.py", line 98, in update
    airdate_dt = datetime.strptime(airdate_str, "%Y-%m-%d %A %I:%M %p")
  File "/usr/local/lib/python3.9/_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "/usr/local/lib/python3.9/_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '2022-03-27 dimanche 10:00 ' does not match format '%Y-%m-%d %A %I:%M %p'
```

i try to modify this line in your code : 

```python
airdate_dt = datetime.strptime(airdate_str, "%Y-%m-%d %A %H:%M ")
```

But without result :) if ytou have an idea

Thanks again for your work

**Comment by IDmedia** [comment]
Please try the latest version and let me know if the error persists :)
